version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
  piwik:
    image: 'bitnami/piwik:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - '3004:80'
    depends_on:
      - mariadb
    volumes:
      - 'piwik_data:/bitnami'
volumes:
  mariadb_data:
    driver: local
  piwik_data:
    driver: local
